### ISSUE TITLE
Git Inspector의 기능 파악하기

### ISSUE THREAD

**Issue by hohyunjun** [kookmin-sw/2018-cap1-6#1]
프로젝트에 쓰일 Git inspector에 어떤 기능이 있는지 명확히 파악한다.

**Comment by ghost** [comment]
# 기본 정보
- 커밋 횟수
- 삽입 라인
- 삭제 라인 
- 변화 수 
- 나이 =  유저가 적은 모든 줄의 평균 지난 일수,
- 안정성 = 유저가 적은 라인이 지금까지 살아남아 있는 비율,
- 코멘트 비율 = 전체 줄 수 대비 주석 비율.

# 옵션
- —format : 분석 결과를 내가 원하는 파일로 만들어 줌 = html,json 등등.
- —grading : 더 자세한 결과를 보여줌.
날짜별 소스코드 생산 라인 수(timeline),
어떤 소스코드에 가장 많이 커밋 했는가.
- -f : 특정 확장자 파일만 검색.
- -H : 중복을 더 엄격하게 찾음?
- -m: 순환 복잡도 체크

### 이하 4개를 조합해서 날짜 조건 주게 할 수 있을듯 함.

- -T : 월별 커밋 횟수
- -w와 같이 쓰면 주별로 변경 가능.
- —since=날짜 : 특정 날짜 이후 커밋만 검색
- —until = 특정 날짜 이전

### 빌드 파일 등을 이걸로 제외하면 될 듯.
—exclude : 제외할 형식 지정. 

커스터마이징은 gitinspector 폴더 안에 옵션별로 기능 나누어져 있어 그 부분 커스터마이징 하면 될 듯.

**Comment by one10004** [comment]
# 옵션 추가

- -l : 어떤 형식의 파일이 있는지 나타낸다. (ex. md, py, txt .....)

- -r : 각각의 코드 파일에 유저별로 몇 줄을 기여했는지 나타낸다.
